### PR TITLE
feat: add padding for album name one have 1 character

### PR DESCRIPTION
**Pull request by aokblast**
Some albums' name only have 1 character. However, discord's status have to be at least two characters.
Therefore, we add 1 space padding for this case.

### CODE REVIEW

**Comment by jtpox** [comment]
image
There seems to be a problem when I play a certain file your version. On the left is the instance from the main branch, while on the right, your fork. Of course, the two aren't ran at the same time.

The file played was a DFF with no cover and almost no metadata.
image


Also to add, a default image does exist if you are using the default Discord Client ID, but not if you are using your own API keys.

You can add a default image by uploading one to the Discord Developer Portal.
`Applications > Select App > Rich Presence > Art Assets`
Upload a default image there and name it "roon_labs_logo".

**Comment by aokblast** [comment]
For the first problem, I just want to fix the album with only a single word. So maybe I can change the function from < 2 to == 1 that will be compatible with your case.
For the second problem, I think we have to add some comment in the README to notify other suffer from this case instead of changing the source code?
Therefore, I will rebase and adjust this PR properly.

**Comment by aokblast** [comment]
Besides, In RPC, only type watching and playing are allowed as described in [link](https://github.com/discordjs/RPC/pull/149#discussion_r1123577129).

**Comment by jtpox** [comment]
> Besides, In RPC, only type watching and playing are allowed as described in [link](https://github.com/discordjs/RPC/pull/149#discussion_r1123577129).

YES! That's what I've been trying to explain on the other issue haha.

Apologies for the slow reply. As for your new pull request, the issue persists. I have done some tests and have concluded that an empty string of just spaces will not be accepted by Discord RPC.

May I suggest changing the display value of `state` to something like this:
```js
/**
 * WORKS:
 * undefined
 * 
 * NOT WORKING
 * ""
 * false
 */
state: data.now_playing.three_line.line3.substr(0, 128) || undefined,
```
We can choose to display something if `line3` exists and keep it unset if it doesn't.

**Comment by aokblast** [comment]
Oh, sorry. I understand your problem now.
What I want to solve is for the case that the album has only 1 word as the  following picture shows.

CleanShot 2023-09-22 at 22 05 42

Because the state item in the discord should be at least two word, your change will still be failed on my case.  

However, I don't have the album in your case. I want to ask the `data.now_playing.three_line.line3` in the album in your case return undefined or empty string?

If we know the answer, we can further solve this issue.

**Comment by aokblast** [comment]
Update: I make a little change and it still works on my case.
Can you help me test on your case?
Thanks!

**Comment by jtpox** [comment]
Yup it works right now.

The file I played was displayed like this in `data.now_playing`
image

**Comment by aokblast** [comment]
Ok, I think if both of us cases work, you can merge it if there is no problem anymore. XD

**Comment by jtpox** [comment]
> Ok, I think if both of us cases work, you can merge it if there is no problem anymore. XD

Merged, thanks for the pull request!

**Pull request merged**
